Merge upstream 20211118 (#141)
* Remove json type cast for contract msgs

* Update changelog for v0.17.0

* Added compatibilitys

* Go mod tidy

* Use interface for better decoupling

* Allow access to contract address builder

* Remove max gas limit

* Test Pinned contract does not loop forever

* Bump github.com/prometheus/client_golang from 1.10.0 to 1.11.0

Bumps [github.com/prometheus/client_golang](https://github.com/prometheus/client_golang) from 1.10.0 to 1.11.0.
- [Release notes](https://github.com/prometheus/client_golang/releases)
- [Changelog](https://github.com/prometheus/client_golang/blob/master/CHANGELOG.md)
- [Commits](https://github.com/prometheus/client_golang/compare/v1.10.0...v1.11.0)

---
updated-dependencies:
- dependency-name: github.com/prometheus/client_golang
  dependency-type: direct:production
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>

* Add cost and api cost options

* Cleanup keeper result types

* Verify converted coin

* Empty submsg result does not overwrite

* Store contract response in event (#535)

* Store contract response in event

* Review feedback

* Add cli alias (#536)

* Add cli alias

* Review feedback

* Bump github.com/rs/zerolog from 1.22.0 to 1.23.0

Bumps [github.com/rs/zerolog](https://github.com/rs/zerolog) from 1.22.0 to 1.23.0.
- [Release notes](https://github.com/rs/zerolog/releases)
- [Commits](https://github.com/rs/zerolog/compare/v1.22.0...v1.23.0)

---
updated-dependencies:
- dependency-name: github.com/rs/zerolog
  dependency-type: direct:production
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>

* Bump github.com/spf13/viper from 1.7.1 to 1.8.0

Bumps [github.com/spf13/viper](https://github.com/spf13/viper) from 1.7.1 to 1.8.0.
- [Release notes](https://github.com/spf13/viper/releases)
- [Commits](https://github.com/spf13/viper/compare/v1.7.1...v1.8.0)

---
updated-dependencies:
- dependency-name: github.com/spf13/viper
  dependency-type: direct:production
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>

* Charge gas for custom event attributes and messages (#539)

* Charge gas for custom event attributes

* Introduce gas register for gas costs

* Review feedback

* Tests and minor updates

* Godoc

* Empty (non nil) reply data can overwrites response

* Bump github.com/spf13/viper from 1.8.0 to 1.8.1

Bumps [github.com/spf13/viper](https://github.com/spf13/viper) from 1.8.0 to 1.8.1.
- [Release notes](https://github.com/spf13/viper/releases)
- [Commits](https://github.com/spf13/viper/compare/v1.8.0...v1.8.1)

---
updated-dependencies:
- dependency-name: github.com/spf13/viper
  dependency-type: direct:production
  update-type: version-update:semver-patch
...

Signed-off-by: dependabot[bot] <support@github.com>

* Multiply default wasm size by 2

* Fix test

* Upgrade cosmos-sdk v0.42.6

* Upgrade wasmvm v0.15.x

* Upgrade Dockerfile

* Bump wasmvm and testdata to v0.16.0-rc1

* IBC Code compiles (non-test)

* Keeper tests pass

* all x/wasm tests compile

* Update to cosmwasm 0.16.0-rc3 contracts, with some fixes

* Use _contract_address attribute in emitted events

* Reserve all attributes that start with _

* Test for events returned from IBC

* Return custom events from IBC calls as well

* Contracts to v0.16.0-rc4, wasmvm to v0.16.0-rc2

* Fix tests

* Update Dockerfile

* Add error messages on invalid event attributes

* Tests compile and pass

* Better event tests

* Update with PR comments

* Update buf commands

See https://docs.buf.build/faq/

* Rename 2 fields and regenerate protobuf

* {Init,Migrate}Msg -> Msg in proposals as well

* Changed references in code - 2 broken tests

* Rename remaining {Init,Migrate}Msg fields

* Add CHANGELOG entry

* Update JSON/YAML parsing and test code

* Move proto files to v1

* Recompile protobuf files

* Adapt code to v1beta1 -> v1 rename

* Fix up whitespace issues

* Fixed remaining PR comments

* Add failing tests showing nothing filtered now

* Add filtering to logic, tests pass

* Update CHANGELOG

* Bump github.com/spf13/cast from 1.3.1 to 1.4.0

Bumps [github.com/spf13/cast](https://github.com/spf13/cast) from 1.3.1 to 1.4.0.
- [Release notes](https://github.com/spf13/cast/releases)
- [Commits](https://github.com/spf13/cast/compare/v1.3.1...v1.4.0)

---
updated-dependencies:
- dependency-name: github.com/spf13/cast
  dependency-type: direct:production
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>

* Update hash algorithm

* Update tests (new default contract addr)

* Almost all tests pass

* Update CHANGELOG

* Fix last tests

* PR Comment: move where truncating address length to 20

* Remove source, builder from proto files

* x/wasm/types compiles

* x/wasm/keeper compiled

* keeper and types pass tests

* All code compiles and tests

* Used reserved keyword in protobuf

* Change default message size cost to 0

* Make gas register tests more flexible, fix counting bug

* Adjust gas prices in tests

* Update comments

* Change IBCContractKeeper interface, code builds

* Fix relay tests

* Use v0.16.0-rc5 contracts

* Update gas price

* Bump Cosmos-sdk to v0.42.8

* Remove obsolete cli params

* Add intiial SECURITY.md

* Update CHANGELOG (#577)

* Update CHANGELOG

* Update changelog

* Update changelog

* Add organisation to grpc gateway path

* Cosmos SDK 0.42.9, wasmvm 0.16.0-rc3

* Add contract features to debug logging

(cherry picked from commit ccd075200f704c39ae619d36be781092711bbd41)

* Update Dockerfile

* Use wasmvm 0.16.0

* update test contracts to cosmwasm v0.16.0

* Start documenting events system

* Fill out rest of the skeleton

* Clarified event processing in the sdk

* Import docs on bank / distribution modules

* Split x/wasm events into multiple types, document message concat

* _code_id, document emitting custom events, handling events in reply

* Remove all _code_id references, no injection in wasm events

* Empty Response.attributes -> no wasm event emitted

* Remove submsg_start/stop, improve documentation of flattening

* Remove hex-encoded result attribute

* Use mode: handle_failure/success attribute on reply

* Use shellcheck and shfmt on contrib scripts

This commit does not introduce any functionality change. It is only
applying suggestions from the shellcheck linter and reformats the code
using shfmt.

Shellcheck is a base shell linter that helps avoiding common shell
script mistakes.
Shfmt formats shell code similar to other Xfmt (i.e. gofmt) tools. No
need to format code manually or argue about the style anymore!

Both tools can be integrated with many editors or IDE.

* Refactor events

* Update ibc reflect contract from CosmWasm PR 1046

* Add tests for events

* Strip message events and reorder

* Download cosmwasm contracts

* Add failing testcase showing messages make it into reply block

* One more test for message event without reply

* Filter messages, fix new tests, break older ones

* Update tests to not expect message event

* Remove (now-unneeded) filtering in DefaultWasmVMContractResponseHandler.Handle

* Simplify filter method

* Bump github.com/spf13/cast from 1.4.0 to 1.4.1

Bumps [github.com/spf13/cast](https://github.com/spf13/cast) from 1.4.0 to 1.4.1.
- [Release notes](https://github.com/spf13/cast/releases)
- [Commits](https://github.com/spf13/cast/compare/v1.4.0...v1.4.1)

---
updated-dependencies:
- dependency-name: github.com/spf13/cast
  dependency-type: direct:production
  update-type: version-update:semver-patch
...

Signed-off-by: dependabot[bot] <support@github.com>

* Update changelog

* Keeper tests (#590)

* More keeper tests

x/wasm/keeper tests are extended to test various input validation.
Keeper input is validated before passing to the keeper method when used
within wasmd application. We cannot ensure such validation when this
keeper is used outside of wasmd application. To keep it safe, fully
validate keeper methods input.

hackatom.wasm is loaded into memory during initialization to avoid
reading file in each test separately. Once migrated to go 1.16, embed
package should be used instead.

Run goimport on certain files.

Some comments fixed or removed.

* ensure that creator address is not nil

* Add decorator options

* Bump github.com/rs/zerolog from 1.23.0 to 1.25.0

Bumps [github.com/rs/zerolog](https://github.com/rs/zerolog) from 1.23.0 to 1.25.0.
- [Release notes](https://github.com/rs/zerolog/releases)
- [Commits](https://github.com/rs/zerolog/compare/v1.23.0...v1.25.0)

---
updated-dependencies:
- dependency-name: github.com/rs/zerolog
  dependency-type: direct:production
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>

* Bump wasmvm to v0.16.1

* Fix query handler instantiation

* Optimize BalanceQuery

* Ensure query isolation (#611)

* Ensure query isolation

* Review feedback

* Bump Go version to  1.16 (#612)

* Bump Go version to  1.16

* Update required version in README

* Update changelog

* Bump github.com/spf13/viper from 1.8.1 to 1.9.0

Bumps [github.com/spf13/viper](https://github.com/spf13/viper) from 1.8.1 to 1.9.0.
- [Release notes](https://github.com/spf13/viper/releases)
- [Commits](https://github.com/spf13/viper/compare/v1.8.1...v1.9.0)

---
updated-dependencies:
- dependency-name: github.com/spf13/viper
  dependency-type: direct:production
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>

* Bump dependencies to wasmvm v1.0.0-soon

* Use v1.0.0-soon contracts

* Important: add iterator feature support

* Adjust gas prices for new contracts

* Fix inconsistent return of contractAddress from keeper/init()

This will not affect functionality whatsoever, it just makes for a more consistent code, as discussed in issue #616.

* Handle contract info query

* Implement tx counter for transaction info (#621)

* Implement tx counter for transaction info

* Count tx before pre-conditions

* Doc update

* Add capabilities to begin block

* Upgrade Cosmos-sdk v0.42.10

* Reference standard IBC events

* Treat all contracts as pinned for gas costs in reply

* Adjust gas prices in tests

* Last gas fix

* Query all pinned code ids

* Upgrade wasmvm-v1.0.0-soon2 (#628)

* Upgrade wasmvm-v1.0.0-soon2

* Improve comment on DefaultGasMultiplier

Co-authored-by: Simon Warta <simon@warta.it>

* Benchmarks for gas pricing (#634)

* Run benchmarks on circle CI

* Add benchmark for secp256k1 verification

* Add compilation benchmark

* Move parallelism back to 1 for benchmarks

* Review comments

Co-authored-by: Alex Peters <alpe@users.noreply.github.com>

* Update gas costs (#636)

* Update gas costs

* Review feedback

* Review comments

* Changelog and compatibility map update (#637)

* Changelog + compatibility update

* Review feedback

* Copy over basic bank benchmark from cosmos-sdk

* Use WasmApp as test case

* Run batches of 20tx / block

* Download test contracts

* Set up cw20 transfer test case

* Pull setup code into this dir, so we can use leveldb

* Update contracts

* Add bank/cw20 benchmarks to CI

* Pull out test initialization

* Refactor wasm setup more

* First table tests

* Add leveldb tests

* Setup unused accounts

* All messages send to different recipient

* Initial account creation also creates cw20 balances

* Upgrade wasmvm to v1.0.0-beta

* remove unused flags from cmd prompt

* changelog update

* More bank/cw20 benchmarks (#651)

* Add blocks of 1000 tx

* Increase Block.MasGas for tests/benchmarks

* Add huge initialization

* Go Formatting update (#648)

* make fmt

* changelog update

* Handle error on Address not found

If we use a wallet address which does not exist, it gives the following error: 
```
Error: empty address string is not allowed
```
which is coming from the SDK and confusing to the user. 
The reason is because one error is not handled properly, in the new proposal, the error is handled which returns the following error if the address does not exist:

```
Error: The specified item could not be found in the keyring
```

* Add golangci lint check on pull requests (#645)

* added golangci lint check on pull requests

* changelog update

* updated to use circleci instead of github actions

* testing a golang change

* added workflow

* updated how we find the golangci command in the make file

* using orb for golangci

* Added golangci install make command

* use docker image for golangci

* stop using make in circleci

* reverted golang change to trigger ci

* gofmt

* make fmt

* fixed a few things

* updated version on golintci

* fixed all the lint errors

* check version

* skipped wrongly failing lint

* Revert generated file changes

* fix import grouping, return errors on failures, initialization of arrays revert

* fixed a few lint errors

* addressed more code review comments

* updated with error check

* increased timeout for golangci-lint

* dont format autogenerated files

Co-authored-by: Carlton Hanna <channa@figure.com>

* Format generated files

* Revert error handling on export (#662)

* Fix message representation for signing (#658)

* Introduce RawContractMessage type

* Add json signbytes test for proposals

* No assumptions on MsgIBCSend.data content

* Smart query uses RawContractMessage

* Revert method signature change to be consistent

* Review comment

* Update after discussions

* Add linter name and minor golint related updates (#663)

* Fixed wrong error message when lastCodeID value is incorrect (#644)

* Fixed wrong error message when lastCodeID value is incorrect

* Updated changelog

* removed unused import

* fixed typeo

* Disable false positive

* Added that m1 macs are currently not supported

* Bump github.com/rs/zerolog from 1.25.0 to 1.26.0

Bumps [github.com/rs/zerolog](https://github.com/rs/zerolog) from 1.25.0 to 1.26.0.
- [Release notes](https://github.com/rs/zerolog/releases)
- [Commits](https://github.com/rs/zerolog/compare/v1.25.0...v1.26.0)

---
updated-dependencies:
- dependency-name: github.com/rs/zerolog
  dependency-type: direct:production
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>

* Open read access to sequences

* Limit simulation gas (#674)

* Limit simulation gas

* Put parameters on separate lines

* Bump github.com/cosmos/iavl from 0.17.1 to 0.17.2 (#673)

Bumps [github.com/cosmos/iavl](https://github.com/cosmos/iavl) from 0.17.1 to 0.17.2.
- [Release notes](https://github.com/cosmos/iavl/releases)
- [Changelog](https://github.com/cosmos/iavl/blob/master/CHANGELOG.md)
- [Commits](https://github.com/cosmos/iavl/compare/v0.17.1...v0.17.2)

---
updated-dependencies:
- dependency-name: github.com/cosmos/iavl
  dependency-type: direct:production
  update-type: version-update:semver-patch
...

Signed-off-by: dependabot[bot] <support@github.com>

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* Update changelog for v0.21

* Update Readme

* Bump wasmvm to v1.0.0-beta2 (#676)

* Bump wasmvm to v1.0.0-beta2

* Update changelog

* `find -type f -name '*.go' | xargs fgrep -l '"github.com/CosmWasm/wasmd/' | xargs -i perl -pi -e 's@/CosmWasm/wasmd/@/iov-one/starnamed/@' "{}"`

* `go mod tidy`

* Fix imports

* Fix poorly resolved merge conflicts

* `make proto-gen`

* Bump go version to match Dockerfile

* Leave trailing whitespace in expected test results

* Avoid collisions on command flag shorthands

Co-authored-by: Alex Peters <alpe@users.noreply.github.com>
Co-authored-by: Ethan Frey <ethanfrey@users.noreply.github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: orkunkl <kulceorkun@gmail.com>
Co-authored-by: Piotr Husiatyński <phusiatynski@gmail.com>
Co-authored-by: Piotr Husiatyński <1517+husio@users.noreply.github.com>
Co-authored-by: Assaf Morami <assaf.morami@gmail.com>
Co-authored-by: Simon Warta <simon@warta.it>
Co-authored-by: fkneeland <fkneeland@figure.com>
Co-authored-by: fkneeland-figure <86616427+fkneeland-figure@users.noreply.github.com>
Co-authored-by: Mojtaba <mojtaba-esk@users.noreply.github.com>
Co-authored-by: Carlton Hanna <channa@figure.com>