Authenticate with api.github.com to avoid build failures due to rate limiting
StatusCodeError: 403 - {"message":"API rate limit exceeded for 34.68.144.114. (But here's the good news: Authenticated requests get a higher rate
limit. Check out the documentation for more
details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}